-- Insertar eventos
INSERT INTO eventos (nombre, fecha, lugar) VALUES
('Concierto de Rock', '2025-05-20', 'Estadio Nacional'),
('Feria del Libro', '2025-06-10', 'Centro de Convenciones'),
('Festival de Jazz', '2025-07-15', 'Parque Central'),
('Obra de Teatro', '2025-08-05', 'Teatro Municipal'),
('Exposición de Arte', '2025-09-12', 'Galería Nacional'),
('Conferencia de Tecnología', '2025-10-20', 'Hotel Real'),
('Feria de Empleo', '2025-11-18', 'Centro de Convenciones'),
('Concierto de Pop', '2025-12-25', 'Estadio Nacional'),
('Festival de Cine', '2026-01-10', 'Cine Central'),
('Evento de Caridad', '2026-02-14', 'Parque Central'),
('Competencia de Baile', '2026-03-22', 'Teatro Municipal'),
('Conferencia de Salud', '2026-04-05', 'Hotel Real'),
('Feria de Ciencia', '2026-05-15', 'Centro de Convenciones'),
('Concierto de Clásica', '2026-06-30', 'Estadio Nacional'),
('Festival Gastronómico', '2026-07-20', 'Parque Central');

-- Insertarlocalidades 
INSERT INTO localidades (id_evento, seccion, fila, numero) VALUES
(1, 'VIP', 'A', 1),
(1, 'VIP', 'A', 2),
(1, 'General', 'A', 3),
(1, 'General', 'A', 4),
(1, 'General', 'A', 5),
(2, 'General', 'B', 1),
(2, 'VIP', 'A', 2),
(2, 'VIP', 'A', 3),
(2, 'General', 'B', 4),
(2, 'General', 'C', 5),
(3, 'VIP', 'C', 1),
(3, 'VIP', 'C', 2),
(3, 'General', 'C', 3),
(3, 'General', 'C', 4),
(3, 'General', 'C', 5),
(4, 'VIP', 'A', 1),
(4, 'VIP', 'A', 2),
(4, 'General', 'A', 3),
(4, 'General', 'A', 4),
(4, 'VIP', 'A', 5),
(5, 'General', 'B', 1),
(5, 'VIP', 'A', 2),
(5, 'VIP', 'A', 3),
(5, 'General', 'B', 4),
(5, 'General', 'B', 5),
(6, 'General', 'C', 1),
(6, 'VIP', 'A', 2),
(6, 'VIP', 'A', 3),
(6, 'General', 'C', 4),
(6, 'General', 'C', 5),
(7, 'VIP', 'A', 1),
(7, 'VIP', 'A', 2),
(7, 'General', 'B', 3),
(7, 'General', 'B', 4),
(7, 'General', 'C', 5),
(8, 'General', 'B', 1),
(8, 'VIP', 'A', 2),
(8, 'VIP', 'A', 3),
(8, 'General', 'B', 4),
(8, 'General', 'B', 5),
(9, 'General', 'C', 1),
(9, 'VIP', 'A', 2),
(9, 'VIP', 'A', 3),
(9, 'General', 'C', 4),
(10, 'General', 'C', 5),
(10, 'General', 'C', 1),
(10, 'VIP', 'A', 2),
(10, 'VIP', 'A', 3),
(10, 'General', 'C', 4),
(11, 'General', 'C', 5),
(11, 'General', 'C', 1),
(11, 'VIP', 'A', 2),
(11, 'VIP', 'A', 3),
(11, 'General', 'C', 4),
(12, 'General', 'C', 5),
(12, 'General', 'C', 1),
(12, 'VIP', 'A', 2),
(12, 'VIP', 'A', 3),
(12, 'General', 'C', 4),
(12, 'General', 'C', 5),
(13, 'General', 'C', 1),
(13, 'VIP', 'A', 2),
(13, 'VIP', 'A', 3),
(13, 'General', 'C', 4),
(13, 'General', 'C', 5),
(14, 'General', 'C', 1),
(14, 'VIP', 'A', 2),
(14, 'VIP', 'A', 3),
(14, 'General', 'C', 4),
(14, 'General', 'C', 5),
(15, 'General', 'C', 1),
(15, 'VIP', 'A', 2),
(15, 'VIP', 'A', 3),
(15, 'General', 'C', 4),
(15, 'General', 'C', 5);

-- Insertar usuarios
INSERT INTO usuarios (nombre, email) VALUES
('Juan Pérez', 'juan.perez@example.com'),
('María López', 'maria.lopez@example.com'),
('Carlos Gómez', 'carlos.gomez@example.com'),
('Ana Martínez', 'ana.martinez@example.com'),
('Luis Rodríguez', 'luis.rodriguez@example.com'),
('Sofía Hernández', 'sofia.hernandez@example.com'),
('Pedro Sánchez', 'pedro.sanchez@example.com'),
('Laura Díaz', 'laura.diaz@example.com'),
('Jorge Ramírez', 'jorge.ramirez@example.com'),
('Lucía Torres', 'lucia.torres@example.com'),
('Andrés Morales', 'andres.morales@example.com'),
('Elena Ruiz', 'elena.ruiz@example.com'),
('Diego Fernández', 'diego.fernandez@example.com'),
('Valentina Castro', 'valentina.castro@example.com'),
('Miguel Navarro', 'miguel.navarro@example.com');

-- Insertar reservas
INSERT INTO reservas (id_usuario, id_localidad) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15);
